//! The two sections that are not code: what the file imports, and what it holds.

use crate::ast::{ClassId, EnumId, Ty};
use crate::ir::Program;

use super::asm::Asm;
use super::runtime::{
    ABORTS, ARENA_CHUNK, ARENA_END, ARENA_NEXT, FIRST_READ, INPUT, INPUT_BYTES, INPUT_DONE,
    INPUT_LEN, INPUT_POS, SCRATCH, SCRATCH_CAP, STACK_LIMIT, STDOUT,
};
use super::used::{
    Used, enum_table, enum_variant_text, fixup_label, text_label, variant_value, vtable_header,
    vtable_label,
};
use super::{ENTRY_POINT, Platform, symbol};

/// The format strings `printf` is handed, and the two words a `bool` prints as.
///
/// One per printable *shape* rather than per type: an enum prints the name of
/// its variant and a string prints a buffer, so both go out through `%s`.
pub const FMT_INT: &str = "fmt_int";
pub const FMT_STR: &str = "fmt_str";
pub const FMT_BOOL: &str = "fmt_bool";
pub const BOOL_TRUE: &str = "bool_true";
pub const BOOL_FALSE: &str = "bool_false";

/// What a bare newline is written with, for the two types whose value goes out
/// through a routine rather than a format of its own.
pub const NEWLINE: &str = "fmt_newline";

/// The same format with the line ending already in it, for the last value a
/// `println` writes. One call instead of two, and the second of those used to
/// hand `printf` a format *and* an argument in order to write one character.
pub fn line_format(format: &str) -> String {
    format!("{format}_line")
}

pub fn header(asm: &mut Asm, platform: &dyn Platform, used: &Used) {
    let abi = platform.abi();
    let rule = format!("; {}", "-".repeat(68));

    asm.line(&rule);
    asm.line(&format!("; Generated by tinyc for {} (NASM syntax)", platform.name()));
    asm.line(&rule);
    // Without `default rel`, `lea rcx, [label]` would use a 32-bit absolute
    // address instead of the RIP-relative form 64-bit code wants.
    asm.line("default rel");
    asm.blank();

    // What every C library provides, under the name every C library uses.
    if used.needs_printf() {
        asm.line("extern printf");
    }
    if used.writes_text() {
        // Everything the language writes goes out by *length*, and `fwrite` is
        // the one C library call that takes one and still shares `printf`'s
        // buffered stream — so a program that writes both still comes out in
        // the order it was written. See `runtime::WRITE_TEXT`.
        asm.line("extern fwrite");
    }
    if used.aborts {
        // Reporting a runtime failure needs a stream the compiler can write to
        // without a `FILE*`, and a way out that skips the rest of the program.
        // Only the spelling of the first one differs.
        asm.line(&format!("extern {}", abi.write));
        asm.line("extern exit");
    }
    if used.allocates() {
        // The arena's chunks. Nothing is ever given back, so there is no `free`
        // to declare — see `runtime::arena`.
        asm.line("extern malloc");
    }
    if used.reads_text() {
        // The input is buffered here rather than through a `FILE*`, so a
        // redirected stdin needs the low-level read and nothing else.
        asm.line(&format!("extern {}", abi.read));
    }
    if used.aborts || used.reads_text() {
        // `print` goes through the C runtime, which holds what it is given
        // until the buffer fills. Anything that has to be *seen* before the
        // program blocks or stops has to empty that buffer first.
        asm.line("extern fflush");
    }
    // Whatever this platform alone calls: a console it has to negotiate with,
    // or nothing at all.
    for name in platform.externs(used) {
        asm.line(&format!("extern {name}"));
    }
    asm.line(&format!("global {ENTRY_POINT}"));
    asm.blank();
}

pub fn data_section(asm: &mut Asm, platform: &dyn Platform, program: &Program, used: &Used) {
    asm.line("section .data");
    if used.prints(Ty::Int) {
        asm.asm(&format!("{FMT_INT}: db \"%lld\", 0"));
    }
    // Only an enum still goes out through `%s`: its variants' names are bytes
    // the compiler wrote, so it can promise there is no NUL among them. A
    // string and a character can promise no such thing and are written by
    // length instead.
    if used.prints_enum() {
        asm.asm(&format!("{FMT_STR}: db \"%s\", 0"));
    }
    if used.prints(Ty::Bool) {
        asm.asm(&format!("{FMT_BOOL}: db \"%s\", 0"));
    }
    // The two words are needed whichever format picks between them.
    if used.writes(Ty::Bool) {
        asm.asm(&format!("{BOOL_TRUE}: db \"true\", 0"));
        asm.asm(&format!("{BOOL_FALSE}: db \"false\", 0"));
    }
    // The same three, ending the line, and only the ones a `println` reaches.
    for (ty, format) in
        [(Ty::Int, FMT_INT), (Ty::Enum(EnumId(0)), FMT_STR), (Ty::Bool, FMT_BOOL)]
    {
        if used.ends_a_line(ty) {
            let spec = match ty {
                Ty::Int => "%lld",
                _ => "%s",
            };
            asm.asm(&format!("{}: db \"{spec}\", 10, 0", line_format(format)));
        }
    }
    // No NUL: this is written by length like every other run of bytes.
    if used.writes_a_bare_newline() {
        asm.asm(&format!("{NEWLINE}: db 10"));
    }
    // One method table per class that a `New` builds. Its entries are settled
    // at compile time — a subclass's table is its base's with the overridden
    // slots replaced — so dispatch is a load and an indirect call, and there is
    // nothing to install at startup.
    for (index, slots) in program.vtables.iter().enumerate() {
        if !used.vtables[index] {
            continue;
        }
        let id = ClassId(index as u32);
        let entries: Vec<String> =
            slots.iter().map(|&at| symbol(&program.function(at).name)).collect();
        let label = vtable_label(id);
        // The word in front of the slots: what a fresh copy of this class has
        // to be given of its own, or zero when a copy of it shares nothing.
        // Everything that reads it reaches it as `[vptr-8]`, so it has to be
        // laid down immediately before — and eight-aligned, like the slots.
        let owns = match used.owns_elements(&program.table, id) {
            true => fixup_label(id),
            false => "0".to_string(),
        };
        asm.asm("align 8");
        asm.asm(&format!("{}: dq {owns}", vtable_header(id)));
        match entries.is_empty() {
            // NASM needs something to put there, and nothing will read it.
            true => asm.asm(&format!("{label}: dq 0    ; {} has no methods", label)),
            false => asm.asm(&format!("{label}: dq {}", entries.join(", "))),
        }
    }
    // One table per printed enum: the variant names, and the array of pointers
    // a tag indexes. A tag can only have come from a variant of this very enum,
    // so the index is in range by construction and needs no check.
    // A boxed enum's variants are pointers, so one that carries nothing still
    // has to *be* one. Its value never changes, so it is written down once
    // rather than allocated afresh at every mention.
    for (index, info) in program.table.enums.iter().enumerate() {
        if !used.variant_values[index] {
            continue;
        }
        let id = EnumId(index as u32);
        for (tag, variant) in info.variants.iter().enumerate() {
            if variant.payload.is_empty() {
                asm.asm("align 8");
                asm.asm(&format!(
                    "{}: dq {tag}    ; {}::{}",
                    variant_value(id, tag),
                    info.name,
                    variant.name
                ));
            }
        }
    }
    for (index, info) in program.table.enums.iter().enumerate() {
        if !used.enums[index] {
            continue;
        }
        let id = EnumId(index as u32);
        for (tag, variant) in info.variants.iter().enumerate() {
            asm.asm(&format!("{}: db {}, 0", enum_variant_text(id, tag), bytes_of(&variant.name)));
        }
        let entries: Vec<String> =
            (0..info.variants.len()).map(|tag| enum_variant_text(id, tag)).collect();
        asm.asm(&format!("{}: dq {}", enum_table(id), entries.join(", ")));
    }
    if used.aborts {
        // No NUL: `write` is given a length, not a C string.
        for abort in ABORTS.iter().filter(|a| a.reached_by(used)) {
            asm.asm(&format!("{}: db {}", abort.message(), bytes_of(&abort.text())));
        }
    }
    // Literal text, as the bytes it will be written as. Nothing at run time
    // encodes it, counts it or copies it — which is the whole reason the words
    // around a format's specifiers are not string literals by the time they
    // reach here.
    //
    // No NUL, and no need of one: how many bytes there are was counted while
    // the program was compiled, and it is that count the write is given. It is
    // also what lets a literal hold a `\0` of its own.
    for (index, text) in program.texts.iter().enumerate() {
        asm.asm(&format!("{}: db {}    ; {:?}", text_label(index), bytes_of(text), text));
    }
    // A literal is laid out exactly as a string built at run time is: the
    // character count in the eight bytes before the characters, and the
    // characters four bytes each. That is the whole reason nothing downstream
    // has to know which kind of string it holds.
    for (index, chars) in program.strings.iter().enumerate() {
        let text = chars.iter().collect::<String>().escape_debug().to_string();
        asm.asm("align 8");
        asm.asm(&format!("str{index}_len: dq {}", chars.len()));
        match chars.is_empty() {
            // Nothing may follow the label, and nothing will read it either:
            // its length says there is no character to fetch.
            true => asm.asm(&format!("str{index}:    ; \"\"")),
            false => {
                let values: Vec<String> = chars.iter().map(|c| (*c as u32).to_string()).collect();
                asm.asm(&format!("str{index}: dd {}    ; \"{text}\"", values.join(", ")));
            }
        }
    }
    asm.blank();

    // Uninitialised, so the arena's bookkeeping costs nothing in the file: a
    // next pointer and an end pointer that start equal at zero, which is what
    // sends the very first allocation to ask for a chunk.
    if used.allocates()
        || used.print_str
        || used.reads_text()
        || used.checks_stack
        || used.writes_text()
    {
        asm.line("section .bss");
        // The stream every write goes to, asked for on the first one and kept.
        if used.writes_text() {
            asm.asm(&format!("{STDOUT}: resq 1"));
        }
        // Where the stack ends, worked out once by the entry point. Zero until
        // then, and a zero can never fire the check — which is exactly what the
        // entry point's own prologue needs, since it runs before the answer
        // exists.
        if used.checks_stack {
            asm.asm(&format!("{STACK_LIMIT}: resq 1"));
            platform.stack_bss(asm);
        }
        if used.allocates() {
            asm.asm(&format!("{ARENA_NEXT}: resq 1"));
            asm.asm(&format!("{ARENA_END}: resq 1"));
            asm.asm(&format!("{ARENA_CHUNK}: resq 1"));
        }
        if used.print_str {
            asm.asm(&format!("{SCRATCH}: resq 1"));
            asm.asm(&format!("{SCRATCH_CAP}: resq 1"));
        }
        // The input buffer, and how much of it has been read. Both start at
        // zero, which is what sends the first question to the operating system.
        if used.reads_text() {
            asm.asm(&format!("{INPUT}: resb {INPUT_BYTES}"));
            asm.asm(&format!("{INPUT_POS}: resq 1"));
            asm.asm(&format!("{INPUT_LEN}: resq 1"));
            asm.asm(&format!("{INPUT_DONE}: resq 1"));
            asm.asm(&format!("{FIRST_READ}: resq 1"));
            // Whatever this platform's own way of reading has to remember.
            platform.input_bss(asm);
        }
        asm.blank();
    }
}

pub fn bytes_of(text: &str) -> String {
    text.bytes().map(|b| b.to_string()).collect::<Vec<_>>().join(", ")
}
