; --------------------------------------------------------------------
; Generated by tinyc for x86_64-windows (MASM / ml64 syntax)
;
; vreg  live range   across call  location
; %x    [ 0,  3]        no          r8
; %y    [ 1,  3]        no          r9
; %s    [ 2,  5]       yes         rbx
; %t3   [ 3,  4]        no          r9
; 
; 0 spill slot(s), callee-saved used: rbx
; --------------------------------------------------------------------
option casemap:none

EXTERN printf:PROC

.DATA
    fmt_int db "%lld", 10, 0
    fmt_str db "%s", 10, 0
    str0 db 72, 101, 108, 108, 111, 32, 87, 111, 114, 108, 100, 0    ; "Hello World"

.CODE

main PROC
    ; prologue: save callee-saved registers, then reserve the frame
    push rbx
    sub  rsp, 32    ; 32 bytes of shadow space + 0 spill slot(s) + alignment

    ; %x = 10
    mov  r8, 10

    ; %y = 20
    mov  r9, 20

    ; %s = &str0
    lea  rbx, str0

    ; %t3 = %x + %y
    add  r9, r8

    ; print int %t3
    mov  rdx, r9
    lea  rcx, fmt_int
    call printf

    ; print string %s
    mov  rdx, rbx
    lea  rcx, fmt_str
    call printf

    ; epilogue: return 0 to the CRT
    xor  eax, eax
    add  rsp, 32
    pop  rbx
    ret
main ENDP

END
