//! x86-64 backend for Windows (MASM syntax, assembled by `ml64`).
//!
//! ## Calling convention
//!
//! The generated `main` follows the Microsoft x64 ABI:
//!
//! * integer arguments go in `rcx`, `rdx`, `r8`, `r9`;
//! * the caller reserves 32 bytes of *shadow space* for the callee;
//! * `rsp` must be 16-byte aligned at every `call`;
//! * `rax`, `rcx`, `rdx`, `r8`-`r11` are destroyed by a call, the rest survive.
//!
//! ## Register policy
//!
//! | Role | Registers |
//! |------|-----------|
//! | call arguments, `idiv` remainder (never allocated) | `rcx`, `rdx` |
//! | `idiv` dividend (never allocated)                  | `rax` |
//! | scratch for spilled operands (never allocated)     | `r10`, `r11` |
//! | allocatable, caller-saved                          | `r8`, `r9` |
//! | allocatable, callee-saved                          | `rbx`, `rsi`, `rdi`, `r12`-`r15` |
//!
//! Keeping the ABI-critical registers out of the allocator's hands is what lets
//! the allocator stay target-independent: it only ever sees the last two rows.

use crate::ast::{BinOp, Ty};
use crate::codegen::{Allocation, Backend, Location, PhysReg, RegisterFile};
use crate::ir::{Instr, Program, VReg, Value};

/// Register numbers follow the usual x86-64 encoding order.
const NAMES: [&str; 16] = [
    "rax", "rcx", "rdx", "rbx", "rsp", "rbp", "rsi", "rdi", //
    "r8", "r9", "r10", "r11", "r12", "r13", "r14", "r15",
];

const RAX: &str = "rax";
const RCX: &str = "rcx";
const RDX: &str = "rdx";
/// Holds a spilled destination while it is being computed.
const SCRATCH0: &str = "r10";
/// Holds an immediate or divisor that cannot be an instruction operand.
const SCRATCH1: &str = "r11";

const FMT_INT: &str = "fmt_int";
const FMT_STR: &str = "fmt_str";

/// Bytes of shadow space every caller must reserve on Windows.
const SHADOW_SPACE: u32 = 32;

pub struct X64Windows {
    registers: RegisterFile,
}

impl X64Windows {
    pub fn new() -> X64Windows {
        X64Windows {
            registers: RegisterFile {
                names: NAMES.to_vec(),
                caller_saved: vec![PhysReg(8), PhysReg(9)],
                callee_saved: vec![
                    PhysReg(3),  // rbx
                    PhysReg(6),  // rsi
                    PhysReg(7),  // rdi
                    PhysReg(12), // r12
                    PhysReg(13), // r13
                    PhysReg(14), // r14
                    PhysReg(15), // r15
                ],
            },
        }
    }
}

impl Default for X64Windows {
    fn default() -> Self {
        X64Windows::new()
    }
}

impl Backend for X64Windows {
    fn name(&self) -> &'static str {
        "x86_64-windows"
    }

    fn register_file(&self) -> &RegisterFile {
        &self.registers
    }

    fn emit(&self, program: &Program, allocation: &Allocation) -> String {
        Emitter { program, allocation, backend: self, out: String::new() }.run()
    }
}

struct Emitter<'a> {
    program: &'a Program,
    allocation: &'a Allocation,
    backend: &'a X64Windows,
    out: String,
}

impl<'a> Emitter<'a> {
    fn run(mut self) -> String {
        let frame = FrameLayout::new(self.allocation);
        let program = self.program;

        self.header();
        self.data_section();
        self.line(".CODE");
        self.blank();
        self.line("main PROC");
        self.prologue(&frame);

        for instr in &program.instrs {
            self.blank();
            let described = self.describe(instr);
            self.comment(&described);
            self.instr(instr, &frame);
        }

        self.blank();
        self.epilogue(&frame);
        self.line("main ENDP");
        self.blank();
        self.line("END");
        self.out
    }

    // -- output helpers ----------------------------------------------------

    fn line(&mut self, text: &str) {
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn blank(&mut self) {
        self.out.push('\n');
    }

    fn comment(&mut self, text: &str) {
        self.line(&format!("    ; {text}"));
    }

    fn asm(&mut self, text: &str) {
        self.line(&format!("    {text}"));
    }

    /// `mov` that drops the no-op a reused register often produces.
    fn mov(&mut self, dst: &str, src: &str) {
        if dst != src {
            self.asm(&format!("mov  {dst}, {src}"));
        }
    }

    // -- sections ----------------------------------------------------------

    fn header(&mut self) {
        let rule = format!("; {}", "-".repeat(68));
        let name = self.backend.name();
        let allocation = self.allocation.dump(self.program, self.backend.register_file());

        self.line(&rule);
        self.line(&format!("; Generated by tinyc for {name} (MASM / ml64 syntax)"));
        self.line(";");
        for line in allocation.lines() {
            self.line(&format!("; {line}"));
        }
        self.line(&rule);
        self.line("option casemap:none");
        self.blank();
        self.line("EXTERN printf:PROC");
        self.blank();
    }

    fn data_section(&mut self) {
        let program = self.program;

        self.line(".DATA");
        if self.uses_format(Ty::Int) {
            self.asm(&format!("{FMT_INT} db \"%lld\", 10, 0"));
        }
        if self.uses_format(Ty::Str) {
            self.asm(&format!("{FMT_STR} db \"%s\", 10, 0"));
        }
        for (index, bytes) in program.strings.iter().enumerate() {
            // Emitting raw bytes avoids every MASM string-quoting corner case.
            let values: Vec<String> = bytes
                .iter()
                .map(|b| b.to_string())
                .chain(std::iter::once("0".to_string()))
                .collect();
            let text = String::from_utf8_lossy(bytes).escape_debug().to_string();
            self.asm(&format!("str{index} db {}    ; \"{text}\"", values.join(", ")));
        }
        self.blank();
    }

    fn uses_format(&self, ty: Ty) -> bool {
        self.program
            .instrs
            .iter()
            .any(|instr| matches!(instr, Instr::Print { ty: t, .. } if *t == ty))
    }

    fn prologue(&mut self, frame: &FrameLayout) {
        let saved: Vec<&str> = self
            .allocation
            .used_callee_saved
            .iter()
            .map(|&reg| self.backend.registers.name(reg))
            .collect();
        let slots = self.allocation.spill_slots;

        self.comment("prologue: save callee-saved registers, then reserve the frame");
        for reg in saved {
            self.asm(&format!("push {reg}"));
        }
        self.asm(&format!(
            "sub  rsp, {}    ; {SHADOW_SPACE} bytes of shadow space + {slots} spill slot(s) + alignment",
            frame.size
        ));
    }

    fn epilogue(&mut self, frame: &FrameLayout) {
        let saved: Vec<&str> = self
            .allocation
            .used_callee_saved
            .iter()
            .rev()
            .map(|&reg| self.backend.registers.name(reg))
            .collect();

        self.comment("epilogue: return 0 to the CRT");
        self.asm("xor  eax, eax");
        self.asm(&format!("add  rsp, {}", frame.size));
        for reg in saved {
            self.asm(&format!("pop  {reg}"));
        }
        self.asm("ret");
    }

    // -- instruction selection --------------------------------------------

    fn instr(&mut self, instr: &Instr, frame: &FrameLayout) {
        match instr {
            Instr::Const { dst, val } => {
                let work = self.work_reg(*dst, false);
                self.asm(&format!("mov  {work}, {val}"));
                self.store_back(*dst, &work, frame);
            }
            Instr::StrAddr { dst, id } => {
                let work = self.work_reg(*dst, false);
                self.asm(&format!("lea  {work}, str{}", id.0));
                self.store_back(*dst, &work, frame);
            }
            Instr::Bin { op: BinOp::Div, dst, lhs, rhs } => self.division(*dst, lhs, rhs, frame),
            Instr::Bin { op, dst, lhs, rhs } => {
                // The result usually lands in a register that just held one of
                // the operands — that is register reuse working as intended.
                // Landing on `lhs` is free, because `mov work, lhs` then becomes
                // a no-op; landing on `rhs` would destroy it, so a commutative
                // operator swaps its operands and the rest use a scratch
                // register.
                let (lhs, rhs) = if op.commutes() && self.shares_register(*dst, rhs) {
                    (rhs, lhs)
                } else {
                    (lhs, rhs)
                };
                let clobbers_rhs =
                    self.shares_register(*dst, rhs) && !self.shares_register(*dst, lhs);

                let work = self.work_reg(*dst, clobbers_rhs);
                let lhs = self.value(lhs, frame);
                self.mov(&work, &lhs);

                let (rhs, immediate) = self.operand_for_alu(rhs, frame);
                match op {
                    BinOp::Add => self.asm(&format!("add  {work}, {rhs}")),
                    BinOp::Sub => self.asm(&format!("sub  {work}, {rhs}")),
                    // `imul` has no two-operand immediate form.
                    BinOp::Mul if immediate => self.asm(&format!("imul {work}, {work}, {rhs}")),
                    BinOp::Mul => self.asm(&format!("imul {work}, {rhs}")),
                    BinOp::Div => unreachable!("handled above"),
                }
                self.store_back(*dst, &work, frame);
            }
            Instr::Print { ty, val } => {
                // Load the value first: the format string is a constant, so it
                // can never be clobbered by the argument move.
                let value = self.value(val, frame);
                self.mov(RDX, &value);
                let format = if *ty == Ty::Int { FMT_INT } else { FMT_STR };
                self.asm(&format!("lea  {RCX}, {format}"));
                self.asm("call printf");
            }
        }
    }

    /// `idiv` is fixed to `rdx:rax`, so the dividend is moved into `rax`, sign
    /// extended with `cqo`, and the quotient moved back out.
    fn division(&mut self, dst: VReg, lhs: &Value, rhs: &Value, frame: &FrameLayout) {
        let lhs = self.value(lhs, frame);
        self.mov(RAX, &lhs);
        self.asm("cqo");

        // `idiv` has no immediate form either.
        let divisor = match rhs {
            Value::Const(c) => {
                self.asm(&format!("mov  {SCRATCH1}, {c}"));
                SCRATCH1.to_string()
            }
            Value::Reg(reg) => self.location(*reg, frame),
        };
        self.asm(&format!("idiv {divisor}"));

        // The divisor has already been read, so the quotient can go straight
        // into the destination even if the two share a register.
        let work = self.work_reg(dst, false);
        self.mov(&work, RAX);
        self.store_back(dst, &work, frame);
    }

    /// Where a virtual register lives, as an assembly operand.
    fn location(&self, vreg: VReg, frame: &FrameLayout) -> String {
        match self.allocation.location(vreg) {
            Location::Reg(reg) => self.backend.registers.name(reg).to_string(),
            Location::Spill(slot) => format!("QWORD PTR [rsp+{}]", frame.slot_offset(slot)),
        }
    }

    fn value(&self, value: &Value, frame: &FrameLayout) -> String {
        match value {
            Value::Const(c) => c.to_string(),
            Value::Reg(reg) => self.location(*reg, frame),
        }
    }

    /// Like [`Self::value`], but an immediate too wide for an ALU instruction is
    /// materialised in a scratch register first. Returns whether the resulting
    /// operand is still an immediate.
    fn operand_for_alu(&mut self, value: &Value, frame: &FrameLayout) -> (String, bool) {
        match value {
            Value::Const(c) if i32::try_from(*c).is_err() => {
                self.asm(&format!("mov  {SCRATCH1}, {c}"));
                (SCRATCH1.to_string(), false)
            }
            Value::Const(c) => (c.to_string(), true),
            other => (self.value(other, frame), false),
        }
    }

    /// Whether `value` lives exactly where `dst` will.
    fn shares_register(&self, dst: VReg, value: &Value) -> bool {
        matches!(
            value,
            Value::Reg(other) if self.allocation.location(*other) == self.allocation.location(dst)
        )
    }

    /// The register an instruction computes its result in: the destination's own
    /// register, or a scratch register when the destination is spilled or would
    /// clobber an operand that has not been read yet.
    fn work_reg(&self, dst: VReg, force_scratch: bool) -> String {
        match self.allocation.location(dst) {
            Location::Reg(reg) if !force_scratch => self.backend.registers.name(reg).to_string(),
            _ => SCRATCH0.to_string(),
        }
    }

    /// Move the result out of the scratch register or into its stack slot, if
    /// it was not computed in place.
    fn store_back(&mut self, dst: VReg, work: &str, frame: &FrameLayout) {
        match self.allocation.location(dst) {
            Location::Reg(reg) => {
                let home = self.backend.registers.name(reg);
                if home != work {
                    self.asm(&format!("mov  {home}, {work}"));
                }
            }
            Location::Spill(slot) => {
                self.asm(&format!("mov  QWORD PTR [rsp+{}], {work}", frame.slot_offset(slot)));
            }
        }
    }

    /// The IR instruction, echoed into the assembly as a comment.
    fn describe(&self, instr: &Instr) -> String {
        let value = |v: &Value| match v {
            Value::Const(c) => c.to_string(),
            Value::Reg(r) => format!("%{}", self.program.name_of(*r)),
        };
        match instr {
            Instr::Const { dst, val } => format!("%{} = {val}", self.program.name_of(*dst)),
            Instr::StrAddr { dst, id } => {
                format!("%{} = &str{}", self.program.name_of(*dst), id.0)
            }
            Instr::Bin { op, dst, lhs, rhs } => format!(
                "%{} = {} {} {}",
                self.program.name_of(*dst),
                value(lhs),
                op.symbol(),
                value(rhs)
            ),
            Instr::Print { ty, val } => format!("print {} {}", ty.name(), value(val)),
        }
    }
}

/// Stack frame layout for `main`.
///
/// At function entry `rsp % 16 == 8` (the call pushed a return address). Each
/// pushed register subtracts 8 more, so the frame size is chosen to bring `rsp`
/// back to a 16-byte boundary before any `call`.
struct FrameLayout {
    size: u32,
}

impl FrameLayout {
    fn new(allocation: &Allocation) -> FrameLayout {
        let locals = SHADOW_SPACE + 8 * allocation.spill_slots;
        let mut size = locals.div_ceil(16) * 16;
        if allocation.used_callee_saved.len() % 2 == 0 {
            size += 8;
        }
        FrameLayout { size }
    }

    /// Spill slots sit just above the shadow space.
    fn slot_offset(&self, slot: u32) -> u32 {
        SHADOW_SPACE + 8 * slot
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::regalloc;
    use crate::{lexer, parser, sema};

    fn compile(src: &str) -> String {
        let ast = parser::parse(&lexer::lex(src).unwrap()).unwrap();
        let types = sema::check(&ast).unwrap();
        let ir = crate::ir::lower(&ast, &types);
        let backend = X64Windows::new();
        let allocation = regalloc::allocate(&ir, backend.register_file());
        backend.emit(&ir, &allocation)
    }

    #[test]
    fn frame_keeps_the_stack_aligned_at_calls() {
        for spill_slots in 0..4u32 {
            for pushes in 0..4usize {
                let allocation = Allocation {
                    locations: Default::default(),
                    used_callee_saved: vec![PhysReg(3); pushes],
                    spill_slots,
                    intervals: Vec::new(),
                };
                let frame = FrameLayout::new(&allocation);
                // 8 (return address) + 8*pushes + frame must be a multiple of 16.
                assert_eq!((8 + 8 * pushes as u32 + frame.size) % 16, 0);
                // The frame must still cover shadow space and every spill slot.
                assert!(frame.size >= SHADOW_SPACE + 8 * spill_slots);
            }
        }
    }

    #[test]
    fn emits_a_call_per_print() {
        let asm = compile("int x = 1;\nprint(x);\nprint(x + 1);");
        assert_eq!(asm.matches("call printf").count(), 2);
    }

    #[test]
    fn a_value_live_across_a_call_uses_a_callee_saved_register() {
        let asm = compile("string s = \"hi\";\nprint(1 + 2);\nprint(s);");
        // `s` survives the first printf, so it must be pushed in the prologue.
        assert!(asm.contains("push rbx"), "{asm}");
        assert!(asm.contains("pop  rbx"), "{asm}");
    }

    #[test]
    fn no_pushes_when_nothing_survives_a_call() {
        let asm = compile("print(1 + 2);");
        assert!(!asm.contains("push"), "{asm}");
        assert!(asm.contains("sub  rsp, 40"), "{asm}");
    }

    #[test]
    fn strings_are_emitted_as_bytes() {
        let asm = compile("string s = \"hi\";\nprint(s);");
        assert!(asm.contains("str0 db 104, 105, 0"), "{asm}");
    }
}
